# Tarefa 1 de MAC328 - 28/Fev/2013
# Evandro Fernandes Giovanini nUSP 5173890 

CC = g++
CXX = g++
CFLAGS += 
CXXFLAGS +=

ep : ep.o GRAPHutils.o GRAPHutils.h
	g++ -o ep ep.o GRAPHutils.o

clean :
	rm -f *~ ep GRAPHutils.o ep.o
